name: root
dependencies:
  - python=3.6
  - notebook
  - ipywidgets
  - requests
  - plotly
  # get dependencies for pgcontents
  - certifi
  - click
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  # Additional dependencies
  - numpy 
  - scipy
  - scikit-learn
  - matplotlib 
  - pandas 
  - pillow 
  - graphviz
  - c conda-forge tensorflow
  - pip:
    - git+git://github.com/pl31/pgcontents.git
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
    - graphviz
    - keras
    - seaborn
